=== raneenmahmoud/XML_Labs_ITI/Day2/Part1/employees.dtd
<?xml version="1.0" encoding="UTF-8"?>
  <!ELEMENT Employees (Employee*)>
  <!ELEMENT Employee (Name, Phones, Addresses, Email)>
  <!ELEMENT Name (#PCDATA)>
  <!ELEMENT Phones (Phone*)>
  <!ELEMENT Phone (#PCDATA)>
  <!ATTLIST Phone Type CDATA #REQUIRED>
  <!ELEMENT Addresses (Address*)>
  <!ELEMENT Address (Street, BuildingNumber, Region, City, Country)>
  <!ELEMENT Street (#PCDATA)>
  <!ELEMENT BuildingNumber (#PCDATA)>
  <!ELEMENT Region (#PCDATA)>
  <!ELEMENT City (#PCDATA)>
  <!ELEMENT Country (#PCDATA)>
  <!ELEMENT Email (#PCDATA)>

=== raneenmahmoud/XML_Labs_ITI/Day2/Part2/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Employees SYSTEM "employees.dtd">
<?xml-stylesheet type="text/css" href="employee.css"?>

<Employees>
  <Employee>
    <Name>Raneen</Name>
    <Phones>
      <Phone Type="home">5029371</Phone>
      <Phone Type="mobile">011000000000</Phone>
    </Phones>
    <Addresses>
      <Address>
        <Street>Main St.</Street>
        <BuildingNumber>11</BuildingNumber>
        <Region>wengt</Region>
        <City>Aleaxandria</City>
        <Country>Egypt</Country>
      </Address>
      <Address>
        <Street>2nd St.</Street>
        <BuildingNumber>10</BuildingNumber>
        <Region>mohamed faried</Region>
        <City>Aleaxandria</City>
        <Country>Egypt</Country>
      </Address>
    </Addresses>
    <Email>raneen@gmail.com</Email>
  </Employee>
  <Employee>
    <Name>Fayza</Name>
    <Phones>
      <Phone Type="home">5029371</Phone>
      <Phone Type="mobile">0110000000001</Phone>
    </Phones>
    <Addresses>
      <Address>
        <Street>3nd St.</Street>
        <BuildingNumber>10</BuildingNumber>
        <Region>wenget</Region>
        <City>Aleaxandria</City>
        <Country>Egypt</Country>
      </Address>
    </Addresses>
    <Email>toty@gmail.com</Email>
  </Employee>
</Employees>
